#!/bin/bash

ng new angular-ngx-charts --directory ./

Which stylesheet format would you like to use?
Sass (SCSS) [ https://sass-lang.com/documentation/syntax#scss ]

Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? No

$ npx @angular/cli ai init
Agents.md [ https://agents.md/ ]

ng s -o

npm install @angular/animations@^22.0.0 --save
// add charts
npm install @swimlane/ngx-charts --save --legacy-peer-deps

[https://angular.dev/cli/generate/class]

ng generate c features/charts
ng generate c features/powered