#!/bin/bash

ng new rdm-labs --directory ./

Which stylesheet format would you like to use?
Sass (SCSS) [ https://sass-lang.com/documentation/syntax#scss ]

Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? No

$ npx @angular/cli ai init
Agents.md [ https://agents.md/ ]

ng s -o

touch public/data/projects.json

# Generate a new component [https://angular.dev/cli/generate/class]

ng generate c features/home
ng generate c features/project-detail
ng generate c features/powered

ng generate i core/models/project.model
ng generate s core/services/project.service